/// Trilingual strings (fr/ar/en), ported from the approved web prototype.
/// Kept as plain maps for velocity; migrate to ARB/gen-l10n when stable.
/// NOTE: edit ONLY with UTF-8-safe tools — shell regex passes corrupt Arabic.
class S {
  static const Map<String, Map<String, String>> _s = {
    'fr': {
      'app': 'Rad Balek',
      'tagline': 'Alerte précoce · Algérie',
      'mywilayas': 'Mes wilayas',
      'official': 'Alertes officielles',
      'observed': 'Incidents observés',
      'unofficial': 'NON OFFICIEL',
      'byhazard': 'Situation par aléa',
      'nav_alerts': 'Alertes',
      'nav_map': 'Carte',
      'nav_report': 'Signaler',
      'nav_settings': 'Réglages',
      'natl': 'Vigilance nationale',
      'until': "valable jusqu'à",
      'wilayas_red': 'wilayas en rouge',
      'today': "aujourd'hui",
      'what': 'Quoi',
      'where': 'Où',
      'when': 'Quand',
      'action': 'Que faire',
      'source': 'Source',
      'call': 'Appeler le 14',
      'live': 'en direct',
      'offline': 'hors ligne',
      'updated': 'mis à jour',
      'red': 'Vigilance rouge',
      'orange': 'Vigilance orange',
      'yellow': 'Vigilance jaune',
      'heat': 'Canicule',
      'storm': 'Orages',
      'wind': 'Vent fort',
      'sandstorm': 'Tempête de sable',
      'flood': 'Pluies/Inondations',
      'cold': 'Froid/Neige',
      'fire': 'Feu de forêt',
      'road': 'Accident de la route',
      'sat': 'Point chaud satellite',
      'ongoing': 'en cours',
      'contained': 'maîtrisé',
      'extinguished': 'éteint',
      'reported': 'signalé',
      'corr': 'corroboré',
      'det': 'détections',
      'detected': 'Détecté',
      'intensity': 'Intensité du feu',
      'corr_pc': 'Corroboré — Protection Civile',
      'not_corr': 'Satellite seul — non corroboré',
      'fire_safety': 'Éloignez-vous, évitez la fumée. Urgence : appelez le 14.',
      'fi_low': 'faible', 'fi_mod': 'modérée', 'fi_high': 'forte', 'fi_ext': 'extrême',
      'monitored': '58 wilayas surveillées',
      'report': 'Signaler un danger',
      'rep_cat': 'Que voyez-vous ?',
      'rep_where': 'Où ?',
      'rep_desc': 'Détails (optionnel)',
      'rep_send': 'Envoyer le signalement',
      'rep_sent': 'Merci ! Votre signalement aide à protéger les personnes, la nature et les animaux.',
      'rep_err': "Échec de l'envoi — réessayez",
      'community': 'Signalements citoyens',
      'st_new': 'non vérifié',
      'st_ccf': 'confirmé (communauté)',
      'choose_w': 'Choisir la wilaya…',
      'cat_fire': 'Feu',
      'cat_smoke': 'Fumée',
      'cat_road': 'Danger routier',
      'cat_flood': 'Oued / crue',
      'cat_animal': 'Animal en danger',
      'cat_heat': 'Détresse chaleur',
      'cat_other': 'Autre',
      'map_title': 'Carte de vigilance',
      'map_note': 'Frontières des wilayas issues des alertes ONM (CC BY 4.0) — certaines wilayas du sud apparaîtront automatiquement.',
      'tap_hint': 'Touchez une wilaya',
      'lg_sat': 'Point chaud satellite',
      'lg_pc': 'Feux en cours (Prot. Civile)',
      'lg_no': 'Pas d’alerte',
      'add_my': 'Ajouter à mes wilayas',
      'rm_my': 'Retirer de mes wilayas',
      'no_alert': 'Aucune alerte en cours',
      'set_lang': 'Langue',
      'here': 'Ici',
      'quake': 'Séisme',
      'regions': 'Régions',
      'fc48': 'Prévision 48h',
      'rt_fire': 'Feux', 'rt_quake': 'Séismes', 'rt_heat': 'Chaleur', 'rt_fwi': 'Risque feu',
      'sec_profile': 'Profil & zone',
      'nearby': 'Autour de moi', 'nearby_none': 'Aucun signalement dans vos wilayas',
      'quick_access': 'Accès rapide',
      'tile_alerts_sub': 'Toutes les alertes ONM',
      'tile_nearby_sub': 'Signalements · vos wilayas',
      'tile_terrain_sub': 'Officiel & citoyens',
      'tile_map_sub': '58 wilayas · couches',
      'tile_ai_sub': 'Question sécurité · réponse rapide',
      'terrain_short': 'Terrain',
      'terrain_none': 'Aucun incident ni signalement pour le moment',
      'assistant': 'Assistant', 'ask_hint': 'Posez votre question…',
      'ai_welcome': 'Posez-moi une question sur la sécurité, la météo ou les risques dans votre région.',
      'ai_err': 'Désolé, je n’ai pas pu répondre. Réessayez.',
      'ai_disclaimer': 'Assistant IA — en cas d’urgence, appelez le 14 ou 1021.',
      'q_heat': 'Que faire pendant une canicule ?', 'q_flood': 'Comment me protéger d’une inondation ?',
      'q_quake': 'Que faire pendant un séisme ?', 'q_num': 'Quels sont les numéros d’urgence ?',
      'ai_suggest': 'Suggérer la catégorie (IA)', 'ai_none': 'Catégorie non reconnue — choisissez manuellement',
      'sec_emergency': 'Mode urgence',
      'emg_intro': 'Pour que les alertes rouges vous réveillent même en silencieux ou Ne pas déranger, activez ces deux autorisations :',
      'emg_dnd': 'Autoriser en mode Ne pas déranger',
      'emg_batt': 'Ignorer l’optimisation batterie',
      'emg_on': 'Activé ✓', 'emg_off': 'À activer',
      'voice_toggle': 'Annonce vocale des alertes rouges',
      'voice_note': 'Message parlé (arabe + français) quand une alerte rouge touche vos wilayas, app ouverte.',
      'listen': 'Écouter l’alerte',
      'air': 'Qualité de l’air',
      'aq_good': 'Bonne', 'aq_fair': 'Correcte', 'aq_moderate': 'Moyenne', 'aq_poor': 'Mauvaise', 'aq_veryPoor': 'Très mauvaise',
      'risk_extreme': 'risque extrême',
      'risk_high': 'risque élevé',
      'risk_moderate': 'risque modéré',
      'risk_low': 'risque faible',
      'imp_quake': 'Secousse ressentie. Risque de répliques dans les heures qui suivent.',
      'sym_quake': 'Fissures, chutes d’objets, répliques possibles',
      'aid_quake': 'Baissez-vous, abritez-vous, accrochez-vous ; sortez vers un espace dégagé après la secousse ; n’utilisez pas l’ascenseur',
      'add_w': 'Ajouter une wilaya',
      'search': 'Rechercher…',
      'sos_add': 'Ajouter un numéro SOS',
      'directives': 'Directives',
      'safe_btn': 'Je suis en sécurité',
      'fam_title': 'Contacts famille (SMS أنا بخير)',
      'fam_hint': 'Numéro ex : 0550123456',
      'fam_note': 'Le bouton vert envoie un SMS direct à ces numéros.',
      'terrain': 'Terrain — officiel & citoyens',
      'safe_msg': 'أنا بخير — Je suis en sécurité ✓ (envoyé via Rad Balek رد بالك)',
      'onb_lang': 'Choisissez votre langue',
      'onb_wil': 'Choisissez vos wilayas',
      'onb_expl': 'Comprendre les alertes',
      'onb_expl_txt': 'Jaune : soyez attentif. Orange : soyez très vigilant. Rouge : danger — suivez les consignes. Le rouge sonne toujours, même en mode silencieux.',
      'onb_done': 'Commencer',
      'test_btn': 'Tester mes notifications',
      'test_ok': 'Envoyé ✓ Verrouillez l\'écran maintenant — la sirène sonne dans 8 secondes 🔒',
      'pick_contact': 'Depuis les contacts',
      'feels': 'Ressenti',
      'src_official': 'OFFICIEL',
      'test_fail': 'Échec du test',
      'test_sending': 'Envoi du test…',
      'test_noperm': 'Notifications bloquées — autorisez-les dans les réglages',
      'open': 'Ouvrir',
      'share': 'Partager',
      'history': 'Historique (7 jours)',
      'quiet_note': 'La nuit, activez « Ne pas déranger » : l’orange devient silencieux, le rouge sonne quand même.',
      'ch_red': 'Son des alertes rouges',
      'ch_orange': 'Son des alertes oranges',
      'layer_vig': 'Vigilance',
      'layer_t': 'Température',
      'layer_w': 'Vent',
      'layer_h': 'Humidité',
      'follow': 'Alertes à ma position',
      'cond': 'Conditions actuelles',
      'sym': 'Signes d’alerte',
      'aid': 'Premiers secours',
      'sym_heat': 'Confusion, peau chaude et sèche, nausées, pouls rapide, maux de tête violents',
      'aid_heat': 'Mettre à l’ombre, rafraîchir le corps (eau, linge humide), faire boire si conscient — appelez le 14 si les signes persistent',
      'sym_flood': 'Montée rapide de l’eau, courant sur la chaussée, grondement dans l’oued',
      'aid_flood': 'Ne traversez jamais ; gagnez un point haut ; véhicule emporté : sortez et appelez le 14',
      'set_wilayas': 'Mes wilayas (abonnements)',
      'set_notif': 'Alertes par aléa',
      'set_notif_note': 'La vigilance rouge reste toujours active pour vos wilayas. Ces préférences s’appliquent aux notifications push.',
      'set_emerg': 'Numéros d’urgence',
      'em_pc': 'Protection Civile',
      'em_police': 'Police',
      'em_gn': 'Gendarmerie — routes',
      'set_about': 'À propos & sources',
      'export_csv': 'Exporter les signalements (CSV)',
      'about_txt':
          'Rad Balek relaie les alertes officielles (Météo Algérie/ONM, CC BY 4.0), les détections satellite (NASA FIRMS), les bilans de la Protection Civile et les séismes (EMSC) — pour protéger les personnes, la végétation et les animaux dans les 58 wilayas.',
      'kpi_red': 'Wilayas en rouge',
      'kpi_orange': 'Wilayas en orange',
      'kpi_fires': 'Feux en cours',
      'kpi_rep': 'Signalements citoyens',
      'disclaimer':
          'Application d’information — ne remplace pas les consignes officielles. En cas d’urgence, appelez la Protection Civile : 14 ou 1021.',
      'imp_heat':
          'Températures extrêmes dangereuses pour la santé, surtout pour les personnes âgées, les enfants et les travailleurs en extérieur.',
      'imp_storm': 'Orages avec risque de foudre, rafales et pluies intenses.',
      'imp_wind': 'Rafales fortes, objets volants, conduite difficile.',
      'imp_sandstorm': 'Visibilité fortement réduite, air chargé de poussière.',
      'imp_flood': 'Pluies intenses avec risque de crues d’oueds et d’inondations soudaines.',
      'imp_cold': 'Froid intense, verglas et neige possibles.',
    },
    'en': {
      'app': 'Rad Balek',
      'tagline': 'Early warning · Algeria',
      'mywilayas': 'My wilayas',
      'official': 'Official alerts',
      'observed': 'Observed incidents',
      'unofficial': 'UNOFFICIAL',
      'byhazard': 'Situation by hazard',
      'nav_alerts': 'Alerts',
      'nav_map': 'Map',
      'nav_report': 'Report',
      'nav_settings': 'Settings',
      'natl': 'National vigilance',
      'until': 'valid until',
      'wilayas_red': 'wilayas on red',
      'today': 'today',
      'what': 'What',
      'where': 'Where',
      'when': 'When',
      'action': 'What to do',
      'source': 'Source',
      'call': 'Call 14',
      'live': 'live',
      'offline': 'offline',
      'updated': 'updated',
      'red': 'Red alert',
      'orange': 'Orange alert',
      'yellow': 'Yellow alert',
      'heat': 'Heat wave',
      'storm': 'Thunderstorms',
      'wind': 'Strong wind',
      'sandstorm': 'Sandstorm',
      'flood': 'Rain/Flooding',
      'cold': 'Cold/Snow',
      'fire': 'Wildfire',
      'road': 'Road crash',
      'sat': 'Satellite hotspot',
      'ongoing': 'ongoing',
      'contained': 'contained',
      'extinguished': 'extinguished',
      'reported': 'reported',
      'corr': 'corroborated',
      'det': 'detections',
      'detected': 'Detected',
      'intensity': 'Fire intensity',
      'corr_pc': 'Corroborated — Civil Protection',
      'not_corr': 'Satellite only — not corroborated',
      'fire_safety': 'Move away, avoid the smoke. Emergency: call 14.',
      'fi_low': 'low', 'fi_mod': 'moderate', 'fi_high': 'high', 'fi_ext': 'extreme',
      'monitored': '58 wilayas monitored',
      'report': 'Report a danger',
      'rep_cat': 'What do you see?',
      'rep_where': 'Where?',
      'rep_desc': 'Details (optional)',
      'rep_send': 'Send report',
      'rep_sent': 'Thank you! Your report helps protect people, nature and animals.',
      'rep_err': 'Send failed — try again',
      'community': 'Citizen reports',
      'st_new': 'unverified',
      'st_ccf': 'community-confirmed',
      'choose_w': 'Choose wilaya…',
      'cat_fire': 'Fire',
      'cat_smoke': 'Smoke',
      'cat_road': 'Road hazard',
      'cat_flood': 'Oued / flood',
      'cat_animal': 'Animal in danger',
      'cat_heat': 'Heat distress',
      'cat_other': 'Other',
      'map_title': 'Vigilance map',
      'map_note': 'Wilaya boundaries come from ONM alerts (CC BY 4.0) — some southern wilayas will appear automatically.',
      'tap_hint': 'Tap a wilaya',
      'lg_sat': 'Satellite hotspot',
      'lg_pc': 'Ongoing fires (Civil Prot.)',
      'lg_no': 'No alert',
      'add_my': 'Add to my wilayas',
      'rm_my': 'Remove from my wilayas',
      'no_alert': 'No active alert',
      'set_lang': 'Language',
      'here': 'Here',
      'quake': 'Earthquake',
      'regions': 'Regions',
      'fc48': '48h forecast',
      'rt_fire': 'Fires', 'rt_quake': 'Quakes', 'rt_heat': 'Heat', 'rt_fwi': 'Fire risk',
      'sec_profile': 'Profile & zone',
      'nearby': 'Around me', 'nearby_none': 'No reports in your wilayas',
      'quick_access': 'Quick access',
      'tile_alerts_sub': 'All ONM alerts',
      'tile_nearby_sub': 'Reports · your wilayas',
      'tile_terrain_sub': 'Official & citizens',
      'tile_map_sub': '58 wilayas · layers',
      'tile_ai_sub': 'Safety question · fast reply',
      'terrain_short': 'Field',
      'terrain_none': 'No incidents or reports right now',
      'assistant': 'Assistant', 'ask_hint': 'Ask your question…',
      'ai_welcome': 'Ask me anything about safety, weather or hazards in your area.',
      'ai_err': 'Sorry, I couldn’t answer. Try again.',
      'ai_disclaimer': 'AI assistant — in an emergency call 14 or 1021.',
      'q_heat': 'What to do during a heatwave?', 'q_flood': 'How do I stay safe in a flood?',
      'q_quake': 'What to do during an earthquake?', 'q_num': 'What are the emergency numbers?',
      'ai_suggest': 'Suggest category (AI)', 'ai_none': 'Category not recognized — pick manually',
      'sec_emergency': 'Emergency mode',
      'emg_intro': 'So red alerts wake you even in silent or Do Not Disturb, enable these two permissions:',
      'emg_dnd': 'Allow in Do Not Disturb',
      'emg_batt': 'Ignore battery optimization',
      'emg_on': 'On ✓', 'emg_off': 'Enable',
      'voice_toggle': 'Voice announcement for red alerts',
      'voice_note': 'Spoken message (Arabic + French) when a red alert touches your wilayas, app open.',
      'listen': 'Listen to the alert',
      'air': 'Air quality',
      'aq_good': 'Good', 'aq_fair': 'Fair', 'aq_moderate': 'Moderate', 'aq_poor': 'Poor', 'aq_veryPoor': 'Very poor',
      'risk_extreme': 'extreme risk',
      'risk_high': 'high risk',
      'risk_moderate': 'moderate risk',
      'risk_low': 'low risk',
      'imp_quake': 'Shaking felt. Aftershocks possible in the coming hours.',
      'sym_quake': 'Cracks, falling objects, possible aftershocks',
      'aid_quake': 'Drop, cover, hold on; move to open space after shaking; never use elevators',
      'add_w': 'Add wilaya',
      'search': 'Search…',
      'sos_add': 'Add SOS number',
      'directives': 'Directives',
      'safe_btn': "I'm safe",
      'fam_title': 'Family contacts (SMS)',
      'fam_hint': 'Number e.g. 0550123456',
      'fam_note': 'The green button sends a direct SMS to these numbers.',
      'terrain': 'Field — official & citizens',
      'safe_msg': "أنا بخير — I'm safe ✓ (sent via Rad Balek رد بالك)",
      'onb_lang': 'Choose your language',
      'onb_wil': 'Choose your wilayas',
      'onb_expl': 'Understanding alerts',
      'onb_expl_txt': 'Yellow: be attentive. Orange: be very vigilant. Red: danger — follow instructions. Red always rings, even in silent mode.',
      'onb_done': 'Get started',
      'test_btn': 'Test my notifications',
      'test_ok': 'Sent ✓ Lock your screen now — the siren rings in 8 seconds 🔒',
      'pick_contact': 'From contacts',
      'feels': 'Feels like',
      'src_official': 'OFFICIAL',
      'test_fail': 'Test failed',
      'test_sending': 'Sending test…',
      'test_noperm': 'Notifications blocked — allow them in settings',
      'open': 'Open',
      'share': 'Share',
      'history': 'History (7 days)',
      'quiet_note': 'At night, enable Do Not Disturb: orange goes silent, red still rings.',
      'ch_red': 'Red alert sound',
      'ch_orange': 'Orange alert sound',
      'layer_vig': 'Vigilance',
      'layer_t': 'Temperature',
      'layer_w': 'Wind',
      'layer_h': 'Humidity',
      'follow': 'Alerts at my position',
      'cond': 'Current conditions',
      'sym': 'Warning signs',
      'aid': 'First aid',
      'sym_heat': 'Confusion, hot dry skin, nausea, rapid pulse, severe headache',
      'aid_heat': 'Move to shade, cool the body (water, wet cloth), give fluids if conscious — call 14 if signs persist',
      'sym_flood': 'Fast-rising water, current across the road, rumbling in the oued',
      'aid_flood': 'Never cross; reach high ground; if the vehicle is swept, get out and call 14',
      'set_wilayas': 'My wilayas (subscriptions)',
      'set_notif': 'Alerts by hazard',
      'set_notif_note': 'Red vigilance always stays on for your wilayas. These preferences apply to push notifications.',
      'set_emerg': 'Emergency numbers',
      'em_pc': 'Civil Protection',
      'em_police': 'Police',
      'em_gn': 'Gendarmerie — roads',
      'set_about': 'About & sources',
      'export_csv': 'Export citizen reports (CSV)',
      'about_txt':
          'Rad Balek relays official alerts (Météo Algérie/ONM, CC BY 4.0), satellite detections (NASA FIRMS), Civil Protection reports and earthquakes (EMSC) — protecting people, vegetation and animals across all 58 wilayas.',
      'kpi_red': 'Wilayas on red',
      'kpi_orange': 'Wilayas on orange',
      'kpi_fires': 'Ongoing fires',
      'kpi_rep': 'Citizen reports',
      'disclaimer':
          'Informational app — not a substitute for official guidance. In an emergency call Civil Protection: 14 or 1021.',
      'imp_heat': 'Extreme temperatures dangerous to health, especially for the elderly, children and outdoor workers.',
      'imp_storm': 'Thunderstorms with lightning, gusts and heavy rain.',
      'imp_wind': 'Strong gusts, flying objects, difficult driving.',
      'imp_sandstorm': 'Severely reduced visibility, dust-loaded air.',
      'imp_flood': 'Heavy rain with risk of flash floods and oued overflows.',
      'imp_cold': 'Severe cold, black ice and snow possible.',
    },
    'ar': {
      'app': 'رد بالك',
      'tagline': 'إنذار مبكر · الجزائر',
      'mywilayas': 'ولاياتي',
      'official': 'تنبيهات رسمية',
      'observed': 'حوادث مرصودة',
      'unofficial': 'غير رسمي',
      'byhazard': 'الوضع حسب الخطر',
      'nav_alerts': 'التنبيهات',
      'nav_map': 'الخريطة',
      'nav_report': 'إبلاغ',
      'nav_settings': 'الإعدادات',
      'natl': 'اليقظة الوطنية',
      'until': 'صالح حتى',
      'wilayas_red': 'ولايات في الأحمر',
      'today': 'اليوم',
      'what': 'ماذا',
      'where': 'أين',
      'when': 'متى',
      'action': 'ماذا تفعل',
      'source': 'المصدر',
      'call': 'اتصل بـ 14',
      'live': 'مباشر',
      'offline': 'دون اتصال',
      'updated': 'آخر تحديث',
      'red': 'تحذير أحمر',
      'orange': 'تحذير برتقالي',
      'yellow': 'تحذير أصفر',
      'heat': 'موجة حر',
      'storm': 'عواصف رعدية',
      'wind': 'رياح قوية',
      'sandstorm': 'عاصفة رملية',
      'flood': 'أمطار وفيضانات',
      'cold': 'برد وثلوج',
      'fire': 'حريق غابة',
      'road': 'حادث مرور',
      'sat': 'نقطة حرارية (قمر صناعي)',
      'ongoing': 'جارية',
      'contained': 'تحت الحراسة',
      'extinguished': 'أُخمد',
      'reported': 'مبلَّغ عنه',
      'corr': 'مؤكَّد',
      'det': 'رصد',
      'detected': 'رُصد',
      'intensity': 'شدة الحريق',
      'corr_pc': 'مؤكد — الحماية المدنية',
      'not_corr': 'قمر صناعي فقط — غير مؤكد',
      'fire_safety': 'ابتعد وتجنّب الدخان. الطوارئ: اتصل بـ14.',
      'fi_low': 'ضعيفة', 'fi_mod': 'متوسطة', 'fi_high': 'قوية', 'fi_ext': 'شديدة',
      'monitored': '58 ولاية تحت المراقبة',
      'report': 'الإبلاغ عن خطر',
      'rep_cat': 'ماذا ترى؟',
      'rep_where': 'أين؟',
      'rep_desc': 'تفاصيل (اختياري)',
      'rep_send': 'إرسال البلاغ',
      'rep_sent': 'شكرًا! بلاغك يساعد على حماية الناس والطبيعة والحيوانات.',
      'rep_err': 'فشل الإرسال — حاول مجددًا',
      'community': 'بلاغات المواطنين',
      'st_new': 'غير مؤكد',
      'st_ccf': 'مؤكد من المجتمع',
      'choose_w': 'اختر الولاية…',
      'cat_fire': 'حريق',
      'cat_smoke': 'دخان',
      'cat_road': 'خطر على الطريق',
      'cat_flood': 'واد / فيضان',
      'cat_animal': 'حيوان في خطر',
      'cat_heat': 'إجهاد حراري',
      'cat_other': 'آخر',
      'map_title': 'خريطة اليقظة',
      'map_note': 'حدود الولايات مأخوذة من تنبيهات الديوان الوطني للأرصاد الجوية (CC BY 4.0) — بعض ولايات الجنوب ستظهر تلقائيًا.',
      'tap_hint': 'المس ولاية',
      'lg_sat': 'نقطة حرارية (قمر صناعي)',
      'lg_pc': 'حرائق جارية (الحماية المدنية)',
      'lg_no': 'لا تنبيه',
      'add_my': 'أضف إلى ولاياتي',
      'rm_my': 'احذف من ولاياتي',
      'no_alert': 'لا تنبيهات حالية',
      'set_lang': 'اللغة',
      'here': 'هنا',
      'quake': 'زلزال',
      'regions': 'المناطق',
      'fc48': 'توقّعات 48 ساعة',
      'rt_fire': 'الحرائق', 'rt_quake': 'الزلازل', 'rt_heat': 'الحرارة', 'rt_fwi': 'خطر الحريق',
      'sec_profile': 'الملف والمنطقة',
      'nearby': 'حولك', 'nearby_none': 'لا بلاغات في ولاياتك',
      'quick_access': 'وصول سريع',
      'tile_alerts_sub': 'كل تنبيهات الأرصاد',
      'tile_nearby_sub': 'بلاغات · ولاياتك',
      'tile_terrain_sub': 'رسمي ومواطنون',
      'tile_map_sub': '58 ولاية · طبقات',
      'tile_ai_sub': 'سؤال سلامة · رد سريع',
      'terrain_short': 'الميدان',
      'terrain_none': 'لا حوادث ولا بلاغات حاليًا',
      'assistant': 'المساعد', 'ask_hint': 'اطرح سؤالك…',
      'ai_welcome': 'اسألني عن السلامة أو الطقس أو المخاطر في منطقتك.',
      'ai_err': 'عذرًا، تعذّر الرد. حاول مجددًا.',
      'ai_disclaimer': 'مساعد ذكاء اصطناعي — في حالة الطوارئ اتصل بـ14 أو 1021.',
      'q_heat': 'ماذا أفعل أثناء موجة الحر؟', 'q_flood': 'كيف أحمي نفسي من الفيضان؟',
      'q_quake': 'ماذا أفعل أثناء الزلزال؟', 'q_num': 'ما هي أرقام الطوارئ؟',
      'ai_suggest': 'اقترح الفئة (ذكاء اصطناعي)', 'ai_none': 'تعذّر التعرّف — اختر يدويًا',
      'sec_emergency': 'وضع الطوارئ',
      'emg_intro': 'لكي توقظك التنبيهات الحمراء حتى في الوضع الصامت أو عدم الإزعاج، فعّل هذين الإذنين:',
      'emg_dnd': 'السماح في وضع عدم الإزعاج',
      'emg_batt': 'تجاهل توفير البطارية',
      'emg_on': 'مفعّل ✓', 'emg_off': 'تفعيل',
      'voice_toggle': 'إعلان صوتي للتنبيهات الحمراء',
      'voice_note': 'رسالة مسموعة (عربية + فرنسية) عندما يمس تحذير أحمر ولاياتك والتطبيق مفتوح.',
      'listen': 'استمع إلى التنبيه',
      'air': 'جودة الهواء',
      'aq_good': 'جيدة', 'aq_fair': 'مقبولة', 'aq_moderate': 'متوسطة', 'aq_poor': 'سيئة', 'aq_veryPoor': 'سيئة جدًا',
      'risk_extreme': 'خطر شديد',
      'risk_high': 'خطر مرتفع',
      'risk_moderate': 'خطر متوسط',
      'risk_low': 'خطر ضعيف',
      'imp_quake': 'هزة محسوسة. احتمال حدوث هزات ارتدادية في الساعات القادمة.',
      'sym_quake': 'تشققات، سقوط أشياء، هزات ارتدادية محتملة',
      'aid_quake': 'انبطح، احتمِ، تمسّك؛ اخرج إلى مكان مكشوف بعد الهزة؛ لا تستعمل المصعد',
      'add_w': 'أضف ولاية',
      'search': 'ابحث…',
      'sos_add': 'أضف رقم طوارئ',
      'directives': 'التعليمات',
      'safe_btn': 'أنا بخير',
      'fam_title': 'أرقام العائلة (SMS)',
      'fam_hint': 'رقم مثل 0550123456',
      'fam_note': 'الزر الأخضر يرسل SMS مباشرة إلى هذه الأرقام.',
      'terrain': 'الميدان — رسمي ومواطنون',
      'safe_msg': 'أنا بخير — أنا في أمان ✓ (أُرسل عبر رد بالك)',
      'onb_lang': 'اختر لغتك',
      'onb_wil': 'اختر ولاياتك',
      'onb_expl': 'فهم التنبيهات',
      'onb_expl_txt': 'أصفر: كن منتبهًا. برتقالي: كن حذرًا جدًا. أحمر: خطر — اتبع التعليمات. الأحمر يرن دائمًا حتى في الوضع الصامت.',
      'onb_done': 'ابدأ',
      'test_btn': 'اختبار إشعاراتي',
      'test_ok': 'أُرسل ✓ اقفل الشاشة الآن — صفارة الإنذار سترن خلال 8 ثوانٍ 🔒',
      'pick_contact': 'من جهات الاتصال',
      'feels': 'الإحساس',
      'src_official': 'رسمي',
      'test_fail': 'فشل الاختبار',
      'test_sending': 'جارٍ إرسال الاختبار…',
      'test_noperm': 'الإشعارات محظورة — فعّلها في الإعدادات',
      'open': 'فتح',
      'share': 'مشاركة',
      'history': 'السجل (7 أيام)',
      'quiet_note': 'ليلاً فعّل «عدم الإزعاج»: يصمت البرتقالي ويبقى الأحمر يرن.',
      'ch_red': 'صوت التنبيهات الحمراء',
      'ch_orange': 'صوت التنبيهات البرتقالية',
      'layer_vig': 'اليقظة',
      'layer_t': 'الحرارة',
      'layer_w': 'الرياح',
      'layer_h': 'الرطوبة',
      'follow': 'تنبيهات في موقعي',
      'cond': 'الظروف الحالية',
      'sym': 'علامات الخطر',
      'aid': 'الإسعافات الأولية',
      'sym_heat': 'ارتباك، جلد ساخن وجاف، غثيان، نبض سريع، صداع شديد',
      'aid_heat': 'انقل المصاب إلى الظل، برّد جسمه بالماء، اسقه إن كان واعيًا — اتصل بـ14 إذا استمرت الأعراض',
      'sym_flood': 'ارتفاع سريع للمياه، تيار فوق الطريق، هدير في الوادي',
      'aid_flood': 'لا تعبر أبدًا؛ اصعد لمكان مرتفع؛ إن جُرفت السيارة اخرج منها واتصل بـ14',
      'set_wilayas': 'ولاياتي (الاشتراكات)',
      'set_notif': 'التنبيهات حسب الخطر',
      'set_notif_note': 'يبقى التحذير الأحمر مفعّلاً دائمًا لولاياتك. تُطبَّق هذه الخيارات على الإشعارات.',
      'set_emerg': 'أرقام الطوارئ',
      'em_pc': 'الحماية المدنية',
      'em_police': 'الشرطة',
      'em_gn': 'الدرك — الطرقات',
      'set_about': 'حول التطبيق والمصادر',
      'export_csv': 'تصدير البلاغات (CSV)',
      'about_txt':
          'يرحّل «رد بالك» التنبيهات الرسمية (الديوان الوطني للأرصاد الجوية، CC BY 4.0) ورصد الأقمار الصناعية (NASA FIRMS) وبيانات الحماية المدنية والزلازل (EMSC) — لحماية الناس والنباتات والحيوانات في الولايات الـ58.',
      'kpi_red': 'ولايات في الأحمر',
      'kpi_orange': 'ولايات في البرتقالي',
      'kpi_fires': 'حرائق جارية',
      'kpi_rep': 'بلاغات المواطنين',
      'disclaimer': 'تطبيق إعلامي — لا يغني عن التعليمات الرسمية. في حالة الطوارئ اتصل بالحماية المدنية: 14 أو 1021.',
      'imp_heat': 'درجات حرارة قصوى خطيرة على الصحة، خاصة لكبار السن والأطفال والعاملين في الخارج.',
      'imp_storm': 'عواصف رعدية مع خطر البرق والرياح والأمطار الغزيرة.',
      'imp_wind': 'هبوب رياح قوية وأجسام متطايرة وصعوبة في القيادة.',
      'imp_sandstorm': 'انخفاض شديد في الرؤية وهواء محمّل بالغبار.',
      'imp_flood': 'أمطار غزيرة مع خطر فيضان الوديان والسيول المفاجئة.',
      'imp_cold': 'برد قارس مع احتمال الجليد والثلوج.',
    },
  };

  static const Map<String, Map<String, List<String>>> _acts = {
    'fr': {
      'heat': [
        "Buvez de l'eau régulièrement, même sans soif",
        'Évitez le soleil entre 11h et 17h',
        'Prenez des nouvelles des personnes âgées et isolées',
        "Donnez de l'eau et de l'ombre aux animaux",
      ],
      'storm': ['Abritez-vous dans un bâtiment', 'Éloignez-vous des arbres et pylônes', 'Reportez vos déplacements si possible'],
      'wind': ['Fixez les objets extérieurs', 'Prudence en voiture, surtout les poids lourds', 'Éloignez-vous du littoral'],
      'sandstorm': ['Fermez portes et fenêtres', 'Portez un masque à l’extérieur', 'Réduisez la vitesse, allumez les feux'],
      'flood': [
        'Ne traversez jamais un oued en crue, à pied ou en voiture',
        'Éloignez-vous des lits d’oueds et zones basses',
        'Reportez vos déplacements pendant les fortes pluies',
        'Éloignez le bétail des lits d’oueds',
      ],
      'cold': ['Limitez les déplacements sur routes verglacées', 'Chauffez sans obstruer la ventilation (risque CO)', 'Protégez les personnes vulnérables du froid'],
      'quake': ['Baissez-vous, abritez-vous sous une table, accrochez-vous', 'Éloignez-vous des fenêtres et des façades', 'Après la secousse : sortez vers un espace dégagé, sans ascenseur', 'Préparez-vous à des répliques'],
    },
    'en': {
      'heat': ['Drink water regularly, even if not thirsty', 'Avoid the sun between 11:00 and 17:00', 'Check on elderly and isolated people', 'Give animals water and shade'],
      'storm': ['Shelter inside a building', 'Stay away from trees and pylons', 'Postpone travel if possible'],
      'wind': ['Secure outdoor objects', 'Drive carefully, especially high vehicles', 'Stay away from the shoreline'],
      'sandstorm': ['Close doors and windows', 'Wear a mask outdoors', 'Slow down, lights on'],
      'flood': ['Never cross a flooded oued, on foot or by car', 'Stay away from riverbeds and low areas', 'Postpone travel during heavy rain', 'Move livestock away from oued beds'],
      'cold': ['Limit travel on icy roads', 'Heat safely, keep ventilation clear (CO risk)', 'Protect vulnerable people from the cold'],
      'quake': ['Drop, cover under a table, hold on', 'Stay away from windows and facades', 'After shaking: move to open space, never the elevator', 'Expect aftershocks'],
    },
    'ar': {
      'heat': ['اشرب الماء بانتظام حتى دون عطش', 'تجنب الشمس بين 11:00 و17:00', 'اطمئن على كبار السن والمعزولين', 'وفّر الماء والظل للحيوانات'],
      'storm': ['احتمِ داخل مبنى', 'ابتعد عن الأشجار والأعمدة', 'أجّل التنقل إن أمكن'],
      'wind': ['ثبّت الأغراض الخارجية', 'احذر أثناء القيادة خاصة المركبات العالية', 'ابتعد عن الشاطئ'],
      'sandstorm': ['أغلق الأبواب والنوافذ', 'ارتدِ كمامة في الخارج', 'خفف السرعة وأشعل الأضواء'],
      'flood': ['لا تعبر واديًا في حالة فيضان أبدًا، مشيًا أو بالسيارة', 'ابتعد عن مجاري الوديان والمناطق المنخفضة', 'أجّل التنقل أثناء الأمطار الغزيرة', 'أبعد المواشي عن مجاري الوديان'],
      'cold': ['قلل من التنقل على الطرق المتجمدة', 'دفّئ المنزل مع تهوية كافية (خطر الغاز)', 'احمِ الأشخاص الهشين من البرد'],
      'quake': ['انبطح، احتمِ تحت طاولة، تمسّك', 'ابتعد عن النوافذ والواجهات', 'بعد الهزة: اخرج إلى مكان مكشوف دون استعمال المصعد', 'توقّع هزات ارتدادية'],
    },
  };

  static String t(String lang, String key) => _s[lang]?[key] ?? _s['fr']![key] ?? key;

  static List<String> actions(String lang, String hazard) =>
      _acts[lang]?[hazard] ?? _acts[lang]?['heat'] ?? _acts['fr']!['heat']!;

  static String impact(String lang, String hazard) => t(lang, 'imp_$hazard');
}
