name = "aisx-ews-ingest"
main = "worker.js"
compatibility_date = "2026-07-01"

# Poll every 10 minutes (free plan allows cron triggers).
[triggers]
crons = ["*/10 * * * *"]

[[kv_namespaces]]
binding = "EWS_KV"
id = "f7857c1bb59b4c7ca4d34603d057f111"
